# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnboardingChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnboardingChallenge

  target 'OnboardingChallengeTests' do
    inherit! :search_paths
    
    pod 'SnapshotTesting'
  end

end
