# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubApp
  pod 'Kingfisher'

  target 'GitHubAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubAppUITests' do
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.9.0'
  end

end
